#
# Copyright (c) 2004 Specifix, Inc.
# All rights reserved
#

python_files = database.py	\
		__init__.py	\
		localrep.py	\
		sqldb.py	\
		update.py

extra_dist = Makefile

dist_files = $(python_files) $(extra_dist)

all: default-install

install: pyfiles-install

dist: default-dist

clean: default-clean

include ../Make.rules

