#!/usr/bin/python
#
# Copyright (c) 2004 Specifix, Inc.
# All rights reserved
#

import os
import sys
import importrpm
import string
import package
import update
import commit
import srscfg
import cook
import util

cfg = srscfg.SrsConfiguration()

fileDB = cfg.reppath + "/files"
pkgDB = cfg.reppath + "/pkgs"
util.mkdirChain(fileDB, pkgDB)

def usage():
    print "usage: srs import <file.rpm>"
    print "       srs pkglist <pkg>"
    print "       srs update  <pkg>"
    print "       srs commit  <pkg> <version> <root> <filelist>"
    print "       srs cook    <first.recipe> <second.recipe> ..."
    sys.exit(0)

def displayPkgs(reppath, packageList):
    for pkgName in packageList:
	if os.path.isdir(reppath + "/pkgs/" + pkgName):
	    files = os.listdir(reppath + "/pkgs/" + pkgName)
	    for sub in files:
		displayPkgs(reppath, [ pkgName + "/" + sub ])
	else:
	    pkgSet = package.PackageSet(reppath, pkgName)
	    l = pkgSet.versionList()
	    for version in l:
		print "%-24s %s" % (pkgName, version)

if (len(sys.argv) < 2):
    usage()
elif (sys.argv[1] == "import"):
    for file in sys.argv[2:]:
	importrpm.doImport(cfg.reppath, file)
elif (sys.argv[1] == "cook"):
    for file in sys.argv[2:]:
	cook.cook(cfg.reppath, cfg.sourcepath, cfg.buildpath ,file)
elif (sys.argv[1] == "pkglist"):
    if (len(sys.argv) == 2):
	displayPkgs(cfg.reppath, os.listdir(cfg.reppath + "/pkgs"))
    else:
	displayPkgs(cfg.reppath, sys.argv[2:])
elif (sys.argv[1] == "update"):
    for pkg in sys.argv[2:]:
	update.doUpdate(cfg.reppath, cfg.root, cfg.sourcepath, pkg, 
			binaries = 1, sources = 1)
elif (sys.argv[1] == "config"):
    if (len(sys.argv) > 2):
	usage()
    else:
	cfg.display()
elif (sys.argv[1] == "commit"):
    if (len(sys.argv) != 6 or sys.argv[3][0] != "/"):
	print "usage: srs commit <pkg> <version> <root> <filelist>"
	sys.exit(1)

    commit.doCommit(cfg.reppath, sys.argv[2], sys.argv[3], sys.argv[4], \
		    sys.argv[5])
else:
    usage()
