#!/usr/bin/python2

import os
import sys
import util
import importrpm
import string
import package
import update
import commit

DBPATH=os.getcwd() + "/srsdb"
ROOT=os.getcwd() + "/root"

fileDB = DBPATH + "/files"
pkgDB = DBPATH + "/pkgs"
util.mkdirChain(fileDB, pkgDB)

def usage():
    print "usage: srs import <file.rpm>"
    print "       srs pkglist <pkg>"
    print "       srs update  <pkg>"
    print "       srs commit  <pkg> <version> <root> <filelist>"
    sys.exit(0)

def displayPkgs(DBPATH, packageList):
    for pkgName in packageList:
	pkgSet = package.PackageSet(DBPATH, pkgName)
	l = pkgSet.versionList()
	for version in l:
	    print "%-24s %s" % (pkgName, version)

if (len(sys.argv) < 2):
    usage()
elif (sys.argv[1] == "import"):
    for file in sys.argv[2:]:
	importrpm.doImport(DBPATH, file)
elif (sys.argv[1] == "pkglist"):
    if (len(sys.argv) == 2):
	displayPkgs(DBPATH, os.listdir(DBPATH + "/pkgs"))
    else:
	displayPkgs(DBPATH, sys.argv[2:])
elif (sys.argv[1] == "update"):
    for pkg in sys.argv[2:]:
	update.doUpdate(DBPATH, ROOT, pkg)
elif (sys.argv[1] == "commit"):
    if (len(sys.argv) != 6 or sys.argv[3][0] != "/"):
	print "usage: srs commit <pkg> <version> <root> <filelist>"
	sys.exit(1)

    commit.doCommit(DBPATH, sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
else:
    usage()
