#
# Copyright (c) 2004 Specifix, Inc.
# All rights reserved
#

python_files =  __init__.py		\
		deptable.py		\
		flavors.py		\
		idtable.py		\
		instances.py		\
		instructionsets.py	\
		items.py		\
		trovecontents.py	\
		trovestore.py		\
		versionops.py

extra_dist = Makefile
dist_files = $(python_files) $(extra_dist)

all: default-all

install: pyfiles-install

dist: default-dist

clean: default-clean

include ../../Make.rules

