#
# Copyright (c) 2005-2006 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.opensource.org/licenses/cpl.php.
#
# This program is distributed in the hope that it will be useful, but
# without any waranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

python_files = schema.py  sqlite2mysql.py  sqlite2pgsql.py sqlite2sqlite.py

extra_dist =

dist_files = $(python_files) $(extra_dist)

SUBDIRS	=

all: default-subdirs default-all

dist: default-dist

clean: default-clean

include ../../Make.rules
