#!/bin/sh
#
# Copyright (c) rPath, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

bindir=$(dirname $0)
bin=$(basename $0)
importdir=$(cd $bindir/.. 2> /dev/null && pwd -P;)
PYTHON=/usr/bin/python
export PYTHONPATH=$importdir:$PYTHONPATH
exec $PYTHON $importdir/commands/$bin "$@"
