#!/usr/bin/env python2.4
# -*- python -*-
#
# Copyright (c) 2004 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.opensource.org/licenses/cpl.php.
#
# This program is distributed in the hope that it will be useful, but
# without any waranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

import sys

if __name__ == "__main__":
    # ondemand importing for conary command line tool 
    # - but don't impose it on others!  They can load it on their own if they
    # want.
    from conary.lib import importer
    importer.install()

from conary import cvc

if __name__ == "__main__":
    sys.exit(cvc.main())
