#
# Copyright (c) 2004 Specifix, Inc.
# All rights reserved
#

all:
	$(PYTHON) setup.py build
	$(PYTHON) setup.py install --install-lib=..

install:
	$(PYTHON) setup.py --root=$(DESTDIR) install

include ../Make.rules