#!/usr/bin/python2.4
# -*- mode: python -*-
#
# Copyright (c) 2006 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.opensource.org/licenses/cpl.php.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#
#

import os
import sys

if os.path.dirname(sys.argv[0]) != ".":
    if sys.argv[0][0] == "/":
        fullPath = os.path.dirname(sys.argv[0])
    else:
        fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.insert(0, os.path.dirname(fullPath))

import optparse, tarfile

from conary import files, trove
from conary.lib import util
from conary.repository import changeset

sys.excepthook = util.genExcepthook(debug=True)

parser = optparse.OptionParser(version = '%prog 0.1')
(options, args) = parser.parse_args()

if len(args) != 1:
    print >> sys.stderr, "ccs2tar: a single path name was expected"
    sys.exit(1)

try:
    cs = changeset.ChangeSetFromFile(args[0])
except Exception, e:
    print >> sys.stderr, "failed to open %s: %s" % (args[0], str(e))
    sys.exit(1)

if not cs.isAbsolute():
    print >> sys.stderr, "ccs2tar: absolute change set expected"
    sys.exit(1)

troveList = [ trove.Trove(x) for x in cs.iterNewTroveList() ]
fileList = []
for trv in troveList:
    fileList.extend([ (x[0], x[1], x[2]) for x in trv.iterFileList() ])
fileList.sort()

del troveList

tf = tarfile.TarFile("", "w", sys.stdout)

for pathId, path, fileId in fileList:
    stream = cs.getFileChange(None, fileId)
    f = files.ThawFile(stream, pathId)

    if path[0] == '/':
        path = path[1:]

    tarInfo = tarfile.TarInfo(path)

    tarInfo.mtime = f.inode.mtime()
    tarInfo.size = 0
    tarInfo.mode = f.inode.perms()
    tarInfo.uid = 0
    tarInfo.gid = 0
    tarInfo.uname = f.inode.owner()
    tarInfo.gname = f.inode.group()

    if isinstance(f, files.RegularFile):
        tarInfo.size = f.contents.size()
        tarInfo.type = tarfile.REGTYPE
        fObj = cs.getFileContents(pathId)[1].get()
    elif isinstance(f, files.Directory):
        tarInfo.type = tarfile.DIRTYPE
    elif isinstance(f, files.SymLink):
        tarInfo.type = tarfile.SYMTYPE
        tarInfo.linkname = f.target()
    else:
        print >> sys.stderr, "ccs2tar doesn't know about file type %s", \
                    stream[0]
        sys.exit(0)

    tf.addfile(tarInfo, fObj)

