#!/bin/bash

#repPath=$(conary config | grep repPath | awk '{print $2}')
# temporary override
#repPath=http://conary:conary@lambchop/distro/

if [ $0 = "changemail" ]; then
    CONARY=../conary
else
    CONARY=$(echo $0 | sed 's|/[^/]*$||')/../conary
fi

usage ()
{
    (echo "Usage: changemail --reppath <repPath> --trove <trove> --version <version> "
     echo "                 --email <email>"
     echo "       changemail --reppath <repPath> <trove> <version> <email>"
     echo "(using command $CONARY)"
     #echo "default repPath: ${repPath}"
    ) 1>&2
    exit 1
}

if [ $# -eq 0 ] ; then
    usage
fi

while [ $# -gt 0 ] ; do
    case $1 in
	--reppath)
	    shift
	    repPath=$1
	    shift
	    ;;
	--trove)
	    shift
	    trove=$1
	    shift
	    ;;
	--email)
	    shift
	    email=$1
	    shift
	    ;;
	--version)
	    shift
	    version=$1
	    shift
	    ;;
	*)
	    if [ -z "$trove" ] ; then
		trove=$1
	    elif [ -z "$version" ] ; then
		version=$1
	    elif [ -z "$email" ] ; then
		email=$1
	    else
		usage
	    fi
	    shift
	    ;;
    esac
done

if [ -z "$repPath" ]; then
    echo "reppath must be set" >&2
    exit 1
fi

$CONARY src rdiff --reppath $repPath $trove -1 $version 
$CONARY src rdiff --reppath $repPath $trove -1 $version | \
    mail -s "$trove $version" $email
