#!/bin/bash
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


if [ $# -lt 1 ]; then
	echo "Usage: $0 "'"command that failed"'
	echo "Example:"
	echo "$0 "'"conary update gaim"'
	exit
fi

tmpDir="/tmp/conaryError"
if [ ! -d "$tmpDir" ]; then
	echo "Assembling useful debugging information, please wait."
	mkdir $tmpDir
        echo "Error recorded at `date`" > $tmpDir/submit.script
	echo "Conary version:" >> $tmpDir/submit.script
	conary --version >> $tmpDir/submit.script 2>&1
	echo "Conary command that causes the problem:" >> $tmpDir/submit.script 2>&1
	echo "$1" >> $tmpDir/submit.script 2>&1
	echo "(run in this case with --debug=all)" >> $tmpDir/submit.script 2>&1

	$1 --debug=all >> $tmpDir/submit.script 2>&1
	conary q --full-versions --flavors --debug=all --components &> $tmpDir/conary.q
	conary config --debug > $tmpDir/conary.config  2>&1
	tar jcvf $tmpDir/submit.tar.bz2 /var/log/conary /var/lib/conarydb/manifest $tmpDir/submit.script $tmpDir/conary.config $tmpDir/conary.q > /dev/null 2>&1
	echo "Please submit $tmpDir/submit.tar.bz2 to rPath at http://issues.rpath.com/"
        echo "Then, delete $tmpDir (rm -r $tmpDir)"
else
	echo "Please inspect and delete $tmpDir (rm -r $tmpDir)"
fi
