#!/bin/bash
#
# Copyright (c) rPath, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


if [ $# -lt 1 ]; then
	echo "Usage: $0 "'"command that failed"'
	echo "Example:"
	echo "$0 "'"conary update gaim"'
	exit
fi

tmpDir="/tmp/conaryError"
if [ ! -d "$tmpDir" ]; then
	echo "Assembling useful debugging information, please wait."
	mkdir $tmpDir
        echo "Error recorded at `date`" > $tmpDir/submit.script
	echo "Conary version:" >> $tmpDir/submit.script
	conary --version >> $tmpDir/submit.script 2>&1
	echo "Conary command that causes the problem:" >> $tmpDir/submit.script 2>&1
	echo "$1" >> $tmpDir/submit.script 2>&1
	echo "(run in this case with --debug=all)" >> $tmpDir/submit.script 2>&1

	$1 --debug=all >> $tmpDir/submit.script 2>&1
	conary q --full-versions --flavors --debug=all --components &> $tmpDir/conary.q
	conary config --debug > $tmpDir/conary.config  2>&1
	tar jcvf $tmpDir/submit.tar.bz2 /var/log/conary /var/lib/conarydb/manifest $tmpDir/submit.script $tmpDir/conary.config $tmpDir/conary.q > /dev/null 2>&1
	echo "Please submit $tmpDir/submit.tar.bz2 to rPath at http://issues.rpath.com/"
        echo "Then, delete $tmpDir (rm -r $tmpDir)"
else
	echo "Please inspect and delete $tmpDir (rm -r $tmpDir)"
fi
