#!/bin/bash
#
# Copyright (c) SAS Institute, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# The process for using this script is documented at:
# https://issues.rpath.com/browse/KB-26

# Default proxy/repository. If you have your own rBuilder or Update Service,
# change this to point at your system.
PROXY='updates.sas.com'

# Additional label to pull content from
archive_name="centos6"
APPONLY_LABEL='centos6.rpath.com@rpath:centos-6-common'

# eval echo for brace expansion
BOOTSTRAP_TROVES="$(eval echo 'conary{,:{config,data,doc,python,runtime,supdoc}}')"
flavor="x86_64"

T=$(mktemp -d) || { echo could not make temp dir; exit;}
conary update --no-deps --no-restart --no-interactive --root=$T \
    $BOOTSTRAP_TROVES \
    --config="flavor is: $flavor" \
    --no-recurse \
    --install-label="${APPONLY_LABEL}"
mkdir -p $T/etc/conary/config.d

grouppkgs=$(conary rq group-rpath-packages=$APPONLY_LABEL --full-versions)
cat << EOF > $T/etc/conary/system-model
search $grouppkgs
install conary
EOF
cat << EOF >$T/etc/conary/config.d/apponly
syncCapsuleDatabase False
EOF
cat << EOF >$T/etc/conary/config.d/proxy
proxyMap * conary://${PROXY}
proxyMap * conarys://${PROXY}
EOF

rm -rf $T/var/lib/conarydb/rollbacks/*
echo > $T/var/log/conary
rm $T/var/lib/conarydb/manifest

# This python invocation fixes ownership in the archive,
# which prevents "conary repair" from breaking (CNY-3618)
(cd $T; find . -type f | python -c 'import tarfile, sys
t = tarfile.open(fileobj=sys.stdout, mode="w:gz")
for fn in [x.strip() for x in sys.stdin.readlines()]:
    ti = t.gettarinfo(fn)
    ti.uid = ti.gid = 0
    ti.uname = ti.gname = "root"
    t.addfile(ti, fileobj=file(fn))
t.close()
') > ${archive_name}-${flavor}-apponly.tar.gz
rm -rf $T
