#!/usr/bin/env python
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


# system imports
import sys
import os
import optparse

if os.path.dirname(sys.argv[0]) != ".":
    if sys.argv[0][0] == "/":
        fullPath = os.path.dirname(sys.argv[0])
    else:
        fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.insert(0, os.path.dirname(fullPath))

# conary imports
from conary.lib import util
sys.excepthook = util.genExcepthook(debug=True)
from conary.dbstore import shell, sqlerrors

def usage():
    print 'usage: %s [dbstore driver] [dbstore connection path]' %sys.argv[0]
    sys.exit(1)

def main():
    parser = optparse.OptionParser()
    (options, args) = parser.parse_args()

    if len(args) != 2:
        usage()

    try:
        dbshell = shell.DbShell(driver=args[0], path=args[1])
    except sqlerrors.DatabaseError, e:
        print 'Error:', str(e.args[0])
        sys.exit(1)
    dbshell.cmdloop()

if __name__ == '__main__':
    main()
