#!/usr/bin/env python
#
# Copyright (c) rPath, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


# system imports
import sys
import os
import optparse

if os.path.dirname(sys.argv[0]) != ".":
    if sys.argv[0][0] == "/":
        fullPath = os.path.dirname(sys.argv[0])
    else:
        fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.insert(0, os.path.dirname(fullPath))

# conary imports
from conary.lib import util
sys.excepthook = util.genExcepthook(debug=True)
from conary.dbstore import shell, sqlerrors

def usage():
    print 'usage: %s [dbstore driver] [dbstore connection path]' %sys.argv[0]
    sys.exit(1)

def main():
    parser = optparse.OptionParser()
    (options, args) = parser.parse_args()

    if len(args) != 2:
        usage()

    try:
        dbshell = shell.DbShell(driver=args[0], path=args[1])
    except sqlerrors.DatabaseError, e:
        print 'Error:', str(e.args[0])
        sys.exit(1)
    dbshell.cmdloop()

if __name__ == '__main__':
    main()
