#!/usr/bin/env python2.4
# -*- mode: python -*-
#
# Copyright (C) 2005-2006 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.opensource.org/licenses/cpl.php.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

# system imports
import sys
import os
import optparse

if os.path.dirname(sys.argv[0]) != ".":
    if sys.argv[0][0] == "/":
        fullPath = os.path.dirname(sys.argv[0])
    else:
        fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.insert(0, os.path.dirname(fullPath))

# conary imports
from conary.lib import util
sys.excepthook = util.genExcepthook(debug=True)
from conary.dbstore import shell, sqlerrors

def usage():
    print 'usage: %s [dbstore driver] [dbstore connection path]' %sys.argv[0]
    sys.exit(1)

def main():
    parser = optparse.OptionParser()
    (options, args) = parser.parse_args()

    if len(args) != 2:
        usage()

    try:
        dbshell = shell.DbShell(driver=args[0], path=args[1])
    except sqlerrors.DatabaseError, e:
        print 'Error:', str(e.args[0])
        sys.exit(1)
    dbshell.cmdloop()

if __name__ == '__main__':
    main()
