#!/usr/bin/env python
#
# Copyright (c) rPath, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


import os
import sys

if os.path.dirname(sys.argv[0]) != ".":
    if sys.argv[0][0] == "/":
        fullPath = os.path.dirname(sys.argv[0])
    else:
        fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.insert(0, os.path.dirname(fullPath))

from conary.local import journal

j = journal.JobJournal(sys.argv[1])
for kind, entry in j:
    if kind == journal.JOURNAL_ENTRY_RENAME:
        print "rename",
    elif kind == journal.JOURNAL_ENTRY_CREATE:
        print "create",
    elif kind == journal.JOURNAL_ENTRY_REMOVE:
        print "remove",
    elif kind == journal.JOURNAL_ENTRY_BACKUP:
        print "backup",
    elif kind == journal.JOURNAL_ENTRY_MKDIR:
        print "mkdir",
    elif kind == journal.JOURNAL_ENTRY_TRYCLEANUPDIR:
        print "trycleanupdir",
    else:
        assert(0)

    print entry.old(), "->", entry.new(),

    if kind == journal.JOURNAL_ENTRY_BACKUP:
        print "perms=0%o" % entry.inode.perms()

    print
