#!/usr/bin/env python
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


import os
import sys

if os.path.dirname(sys.argv[0]) != ".":
    if sys.argv[0][0] == "/":
        fullPath = os.path.dirname(sys.argv[0])
    else:
        fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.insert(0, os.path.dirname(fullPath))

from conary.local import journal

j = journal.JobJournal(sys.argv[1])
for kind, entry in j:
    if kind == journal.JOURNAL_ENTRY_RENAME:
        print "rename",
    elif kind == journal.JOURNAL_ENTRY_CREATE:
        print "create",
    elif kind == journal.JOURNAL_ENTRY_REMOVE:
        print "remove",
    elif kind == journal.JOURNAL_ENTRY_BACKUP:
        print "backup",
    elif kind == journal.JOURNAL_ENTRY_MKDIR:
        print "mkdir",
    elif kind == journal.JOURNAL_ENTRY_TRYCLEANUPDIR:
        print "trycleanupdir",
    else:
        assert(0)

    print entry.old(), "->", entry.new(),

    if kind == journal.JOURNAL_ENTRY_BACKUP:
        print "perms=0%o" % entry.inode.perms()

    print
