#!/usr/bin/python2.4
# -*- mode: python -*-
#
# Copyright (c) 2004 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.opensource.org/licenses/cpl.php.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#
#

import os
import sys

if os.path.dirname(sys.argv[0]) != ".":
    if sys.argv[0][0] == "/":
        fullPath = os.path.dirname(sys.argv[0])
    else:
        fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.insert(0, os.path.dirname(fullPath))

from conary.repository.filecontainer import FileContainer
from conary.lib.sha1helper import *

f = open(sys.argv[1], "r")
c = FileContainer(f)
if len(sys.argv) == 2:
    rc = c.getNextFile()
    while rc:
	(name, tag, f) = rc
	if len(name) == 16:
	    name = md5ToString(name)

	print "%s (%s)" % (name, tag)
	rc = c.getNextFile()
elif len(sys.argv) == 3:
    name = sys.argv[2]
    if len(name) == 32:
	name = md5FromString(name)

    nf = c.getNextFile()
    while nf:
        (fname, tag, f) = nf
        if fname == name:
            break
        nf = c.getNextFile()

    if not nf:
        if len(name) == 16:
            name = md5ToString(name)
        print "%s not found" % name
        sys.exit(0)

    sys.stdout.write(f.read())
    f.close()
else:
    for file in sys.argv[2:]:
	print "--", file
	f = c.getFile(file)
	sys.stdout.write(f.read())
	print "---"
	f.close()
