#!/bin/sh
thisdir=$(dirname $0)
topdir=$(cd $thisdir/.. 2> /dev/null && pwd -P;)
export PYTHONPATH=$topdir
$thisdir/epydoc --public --html conary -o ../doc/public_api/
$thisdir/epydoc --developer --html conary -o ../doc/developer_api/
