#!/usr/bin/python
#
# Copyright (c) 2011 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.rpath.com/permanent/licenses/CPL-1.0.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

"""
Prompts for a password, then outputs a hash ready for insertion into a
PostgreSQL database.
"""

import getpass
import os
from conary.lib import digestlib
salt = os.urandom(4)
password = getpass.getpass('Password: ')
digest = digestlib.md5(salt + password).hexdigest()
octets = ''.join(r'\\%03o' % ord(x) for x in salt)
print "E'%s', '%s'" % (octets, digest)
