#!/usr/bin/python
#
# Copyright (c) rPath, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


"""
Prompts for a password, then outputs a hash ready for insertion into a
PostgreSQL database.
"""

import getpass
import os
from conary.lib import digestlib
salt = os.urandom(4)
password = getpass.getpass('Password: ')
digest = digestlib.md5(salt + password).hexdigest()
octets = ''.join(r'\\%03o' % ord(x) for x in salt)
print "E'%s', '%s'" % (octets, digest)
