#!/usr/bin/python

import os
import sys

if os.path.dirname(sys.argv[0]):
    if sys.argv[0][0] == "/":
	fullPath = os.path.dirname(sys.argv[0])
    else:
	fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.append(os.path.dirname(fullPath))
from changeset import ChangeSetFromFile
import srscfg
import repository

cfg = srscfg.SrsConfiguration()

repos = repository.Repository(cfg.reppath, "r")

cs = ChangeSetFromFile(sys.argv[1])

newcs = cs.invert(repos)
newcs.formatToFile(cfg, sys.stdout)

if len(sys.argv) > 2:
    newcs.writeToFile(sys.argv[2])
