#!/usr/bin/env python2.4
# -*- mode: python -*-
#
# Copyright (C) 2005-2006 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.opensource.org/licenses/cpl.php.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.

import os
import sys
if 'CONARY_PATH' in os.environ:
    sys.path.insert(0, os.environ['CONARY_PATH'])

from conary import conarycfg
from conary import conaryclient

cfg =conarycfg.ConaryConfiguration(True)
client = conaryclient.ConaryClient(cfg)

if '--all' in sys.argv:
    getAll = True
    sys.argv.remove('--all')
else:
    getAll = False

troveNames = sys.argv[1:]
if not troveNames:
    troveNames = None

localUpdates = client.getPrimaryLocalUpdates(troveNames)

if getAll:
    localUpdates += client.getChildLocalUpdates(client.repos, localUpdates)

for name, oldInfo, newInfo, isAbs in sorted(localUpdates):
    print '%s %s[%s]\n      --> %s[%s]' % (name, oldInfo[0], oldInfo[1], 
                                           newInfo[0], newInfo[1])
