#!/usr/bin/env python
#
# Copyright (c) rPath, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


import os
import sys
if 'CONARY_PATH' in os.environ:
    sys.path.insert(0, os.environ['CONARY_PATH'])

from conary import conarycfg
from conary import conaryclient

cfg =conarycfg.ConaryConfiguration(True)
client = conaryclient.ConaryClient(cfg)

if '--all' in sys.argv:
    getAll = True
    sys.argv.remove('--all')
else:
    getAll = False

troveNames = sys.argv[1:]
if not troveNames:
    troveNames = None

localUpdates = client.getPrimaryLocalUpdates(troveNames)

if getAll:
    localUpdates += client.getChildLocalUpdates(client.repos, localUpdates)

for name, oldInfo, newInfo, isAbs in sorted(localUpdates):
    print '%s %s[%s]\n      --> %s[%s]' % (name, oldInfo[0], oldInfo[1], 
                                           newInfo[0], newInfo[1])
