#!/usr/bin/env python
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


import os
import sys
if 'CONARY_PATH' in os.environ:
    sys.path.insert(0, os.environ['CONARY_PATH'])

from conary import conarycfg
from conary import conaryclient

cfg =conarycfg.ConaryConfiguration(True)
client = conaryclient.ConaryClient(cfg)

if '--all' in sys.argv:
    getAll = True
    sys.argv.remove('--all')
else:
    getAll = False

troveNames = sys.argv[1:]
if not troveNames:
    troveNames = None

localUpdates = client.getPrimaryLocalUpdates(troveNames)

if getAll:
    localUpdates += client.getChildLocalUpdates(client.repos, localUpdates)

for name, oldInfo, newInfo, isAbs in sorted(localUpdates):
    print '%s %s[%s]\n      --> %s[%s]' % (name, oldInfo[0], oldInfo[1], 
                                           newInfo[0], newInfo[1])
