#!/usr/bin/env python2.4
# -*- mode: python -*-
#
# Copyright (c) 2004 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.opensource.org/licenses/cpl.php.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#
#

import crypt
import base64
import getpass
import sys

rand = open("/dev/random", "r")
salt = base64.encodestring(rand.read(6))[:-1]
# $ is magic in md5
salt.replace('$', '%')

pw = getpass.getpass('Password:')
pw2 = getpass.getpass('Password (again):')
if pw != pw2:
    print "Passwords didn't match."
    sys.exit(1)

print crypt.crypt(pw, '$1$%s' % salt)
