#!/usr/bin/python
import os
print "getting package/source versions"
packages=os.popen('''conary rq | grep '^[^:]*\(:source.*\)\?$' ''').readlines()
sourcevers = {}
versions = {}
for p in packages:
    (package,version) = p.split()
    if package.endswith(':source'):
	package = package[:-7]
	sourcevers[package] = version
    else:
	# remove build v
	lastdash = version.rfind('-')
	version = version[:lastdash]
	versions[package] = version

for p in versions.keys():
    if p in sourcevers:
	if sourcevers[p] != versions[p]:
	    print "%-35s%-25s%-20s" % (p + ':', versions[p], sourcevers[p])
