#!/usr/bin/python2.3
# -*- mode: python -*-
#
# Copyright (c) 2004 Specifix, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.opensource.org/licenses/cpl.php.
#
# This program is distributed in the hope that it will be useful, but
# without any waranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

import os
import sys
if os.path.dirname(sys.argv[0]):
    if sys.argv[0][0] == "/":
	fullPath = os.path.dirname(sys.argv[0])
    else:
	fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

fullPath = '/home/dbc/spx/cvs/conary/'

sys.path.append(os.path.dirname(fullPath))

import conarycfg
import util
import helper
sys.excepthook = util.excepthook

cfg = conarycfg.ConaryConfiguration()

repos = helper.openRepository(cfg.repositoryMap)
troves = [ x for x in repos.iterAllTroveNames(cfg.installLabel.getHost()) ]
pkgs = [ p for p in troves if p.find(':') == -1 ]
sources = [ p for p in troves if p.endswith(':source') ]
versions = repos.getTroveLeavesByLabel(pkgs + sources, cfg.installLabel)


pkgs.sort()
for pkg in pkgs:
    sourcepkg = pkg + ':source'
    if pkg in versions and sourcepkg in versions: 
	v = versions[pkg][0]
	sv = versions[sourcepkg][0]
	vt = v.trailingVersion()
	svt = sv.trailingVersion()
	if (v.branch(),vt.getVersion(),vt.getRelease()) != (v.branch(),svt.getVersion(),svt.getRelease()):
		print "%-35s%-25s%-20s" % (pkg, vt.asString(), svt.asString())
