#!/usr/bin/python
#
# Copyright (c) rPath, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


"""
Rebuild repository tables that are derived from other data.
"""

import optparse
from conary import dbstore
from conary.lib import tracelog
from conary.repository.netrepos import accessmap
from conary.server import migrate


def main():
    parser = optparse.OptionParser()
    parser.add_option('-d', '--database', help="PostgreSQL database path")
    parser.add_option('-n', '--dry-run', action='store_true',
            help="Don't perform any actual changes.")
    options, args = parser.parse_args()

    if not options.database:
        parser.error("'database' argument is required")

    tracelog.initLog(level=3)

    db = dbstore.connect(options.database, 'postgresql')
    db.transaction()

    print 'Rebuilding CheckTroveCache'
    migrate.createCheckTroveCache(db)

    print 'Rebuilding UGI and friends'
    accessmap.RoleInstances(db).rebuild()

    if options.dry_run:
        db.rollback()
    else:
        db.commit()


if __name__ == '__main__':
    main()
