#!/usr/bin/python
#
# Copyright (c) 2010 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.rpath.com/permanent/licenses/CPL-1.0.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

"""
Rebuild repository tables that are derived from other data.
"""

import optparse
from conary import dbstore
from conary.lib import tracelog
from conary.repository.netrepos import accessmap
from conary.server import migrate


def main():
    parser = optparse.OptionParser()
    parser.add_option('-d', '--database', help="PostgreSQL database path")
    parser.add_option('-n', '--dry-run', action='store_true',
            help="Don't perform any actual changes.")
    options, args = parser.parse_args()

    if not options.database:
        parser.error("'database' argument is required")

    tracelog.initLog(level=3)

    db = dbstore.connect(options.database, 'postgresql')
    db.transaction()

    print 'Rebuilding CheckTroveCache'
    migrate.createCheckTroveCache(db)

    print 'Rebuilding UGI and friends'
    accessmap.RoleInstances(db).rebuild()

    if options.dry_run:
        db.rollback()
    else:
        db.commit()


if __name__ == '__main__':
    main()
