#!/usr/bin/python
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


"""
Rebuild repository tables that are derived from other data.
"""

import optparse
from conary import dbstore
from conary.lib import tracelog
from conary.repository.netrepos import accessmap
from conary.server import migrate


def main():
    parser = optparse.OptionParser()
    parser.add_option('-d', '--database', help="PostgreSQL database path")
    parser.add_option('-n', '--dry-run', action='store_true',
            help="Don't perform any actual changes.")
    options, args = parser.parse_args()

    if not options.database:
        parser.error("'database' argument is required")

    tracelog.initLog(level=3)

    db = dbstore.connect(options.database, 'postgresql')
    db.transaction()

    print 'Rebuilding CheckTroveCache'
    migrate.createCheckTroveCache(db)

    print 'Rebuilding UGI and friends'
    accessmap.RoleInstances(db).rebuild()

    if options.dry_run:
        db.rollback()
    else:
        db.commit()


if __name__ == '__main__':
    main()
