#!/usr/bin/python
#
# Copyright (c) 2004-2005 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.opensource.org/licenses/cpl.php.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

import sys

from conary import sqlite3
from conary import versions

def renameSeq(s, old, new):
    for l in s.iterLabels():
        if l == old:
            l.host = new.host
            l.namespace = new.namespace
            l.branch = new.branch

def rename(cu, old, new):
    print 'renaming %s to %s' %(old, new)
    oldLabel = versions.Label(old)
    newLabel = versions.Label(new)

    cu.execute("select versionid, version from versions")
    for (versionId, oldVersion) in [ x for x in cu]:
        if not versionId: continue

        vObj = versions.VersionFromString(oldVersion)
        renameSeq(vObj, oldLabel, newLabel)
        version = vObj.asString()

        if oldVersion != version:
            print oldVersion, version

        cu.execute("update versions set version=? where versionid=?", 
                   version, versionId)

    cu.execute("select name from sqlite_master where name='Branches'")
    if cu.fetchone() is not None:
        cu.execute("select branchid, branch from branches")
        for (branchId, oldBranch) in [ x for x in cu]:
            if not branchId: continue

            bObj = versions.VersionFromString(oldBranch)
            renameSeq(bObj, oldLabel, newLabel)
            branch = bObj.asString()

            if oldBranch != branch:
                print oldBranch, branch

            cu.execute("update branches set branch=? where branchid=?", 
                       branch, branchId)

        cu.execute("select labelid, label from labels")
        for (labelId, label) in [ x for x in cu]:
            if not labelId: continue
            label = label.replace(old, new)
            cu.execute("update labels set label=? where labelId=?", 
                       label, labelId)

if len(sys.argv) == 2:
    db = sqlite3.connect(sys.argv[1])
elif len(sys.argv) > 1:
    print "ACK"
    sys.exit(1)
else:
    db = sqlite3.connect("/var/lib/conarydb/conarydb")

cu = db.cursor()

rename(cu, "conary.rpath.com@rpl:1", 
           "conary.rpath.com@something:else")

db.commit()
