#!/usr/bin/env python
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


import sys

from conary import sqlite3
from conary import versions

def renameSeq(s, old, new):
    for l in s.iterLabels():
        if l == old:
            l.host = new.host
            l.namespace = new.namespace
            l.branch = new.branch

def rename(cu, old, new):
    print 'renaming %s to %s' %(old, new)
    oldLabel = versions.Label(old)
    newLabel = versions.Label(new)

    cu.execute("select versionid, version from versions")
    for (versionId, oldVersion) in [ x for x in cu]:
        if not versionId: continue

        vObj = versions.VersionFromString(oldVersion)
        renameSeq(vObj, oldLabel, newLabel)
        version = vObj.asString()

        if oldVersion != version:
            print oldVersion, version

        cu.execute("update versions set version=? where versionid=?", 
                   version, versionId)

    cu.execute("select name from sqlite_master where name='Branches'")
    if cu.fetchone() is not None:
        cu.execute("select branchid, branch from branches")
        for (branchId, oldBranch) in [ x for x in cu]:
            if not branchId: continue

            bObj = versions.VersionFromString(oldBranch)
            renameSeq(bObj, oldLabel, newLabel)
            branch = bObj.asString()

            if oldBranch != branch:
                print oldBranch, branch

            cu.execute("update branches set branch=? where branchid=?", 
                       branch, branchId)

        cu.execute("select labelid, label from labels")
        for (labelId, label) in [ x for x in cu]:
            if not labelId: continue
            label = label.replace(old, new)
            cu.execute("update labels set label=? where labelId=?", 
                       label, labelId)

if len(sys.argv) == 2:
    db = sqlite3.connect(sys.argv[1])
elif len(sys.argv) > 1:
    print "ACK"
    sys.exit(1)
else:
    db = sqlite3.connect("/var/lib/conarydb/conarydb")

cu = db.cursor()

rename(cu, "conary.rpath.com@rpl:1", 
           "conary.rpath.com@something:else")

db.commit()
