#!/usr/bin/env python
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


import os
import sys

if os.path.dirname(sys.argv[0]) != ".":
    if sys.argv[0][0] == "/":
        fullPath = os.path.dirname(sys.argv[0])
    else:
        fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.insert(0, os.path.dirname(fullPath))

import itertools, optparse

from conary import dbstore, trove, versions
from conary.deps import deps
from conary.repository.netrepos import trovestore
from conary.server import schema

parser = optparse.OptionParser(version = '%prog 0.1')
(options, args) = parser.parse_args()

if len(args) != 2:
    print >> sys.stderr, "usage: resha1 <driver> <reposdb>"
    sys.exit(1)

db = dbstore.connect(args[1], driver = args[0])
schema.setupTempTables(db)

cu = db.cursor()

store = trovestore.TroveStore(db)

cu.execute("""
            SELECT instanceId, item, version, flavor FROM Instances 
                JOIN Items ON
                    Instances.itemId = Items.itemId
                JOIN Versions ON
                    Instances.versionId = Versions.versionId
                JOIN Flavors ON
                    Instances.flavorId = Flavors.flavorId
                WHERE
                    Instances.isPresent = 1
           """)

allTroves = [ (x[0], (x[1], versions.VersionFromString(x[2]),
                   deps.ThawFlavor(x[3]))) for x in cu ]

fixes = []
for count, (instanceId, trv) in enumerate(itertools.izip(
            (x[0] for x in  allTroves), 
            store.iterTroves([ x[1] for x in allTroves ]))):
    if count % 50 == 0:
        print "Trove %d of %d\r" % (count, len(allTroves)),
        sys.stdout.flush()

    if trv.verifySignatures():
        continue

    trv.computeSignatures()
    fixes.append((instanceId, trv.troveInfo.sigs.freeze()))

print "%d of %d troves need new sha1s" % (len(fixes), len(allTroves))

cu.execute("CREATE TEMPORARY TABLE Fixes (instanceId INTEGER, sigs BLOB)")
for instanceId, sigs in fixes:
    cu.execute("INSERT INTO Fixes (instanceId, sigs) VALUES (?, ?)",
               instanceId, sigs)

cu.execute("""DELETE FROM TroveInfo WHERE instanceId IN
                    (SELECT instanceId FROM Fixes) AND
                    infoType = %d""" % trove._TROVEINFO_TAG_SIGS)
cu.execute("""INSERT INTO TroveInfo (instanceId, infoType, data)
                SELECT instanceId, %d, sigs FROM Fixes""" 
                            % trove._TROVEINFO_TAG_SIGS)

db.commit()
