#!/usr/bin/env python
# -*- mode: python -*-
#
# Copyright (c) 2004-2008 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.rpath.com/permanent/licenses/CPL-1.0.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

import os
import sys

if os.path.dirname(sys.argv[0]) != ".":
    if sys.argv[0][0] == "/":
        fullPath = os.path.dirname(sys.argv[0])
    else:
        fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.insert(0, os.path.dirname(fullPath))

from conary import rpmhelper

def usage():
    print "Usage: rpm2cpio <rpmpackage> | cpio -ivumd"
    return 1

def main(argv):
    if len(argv) > 2 or len(argv) < 2:
        return usage()
    try:
        r = file(argv[1], 'r')
    except:
        return usage()

    try:
        rpmhelper.extractRpmPayload(r, sys.stdout)
    except rpmhelper.UnknownPayloadFormat, e:
        sys.stderr.write('payload is not in cpio format: %s\n' % e.args[0])
        return 1
    except rpmhelper.UnknownCompressionType, e:
        sys.stderr.write('compression type %s unknown\n' % e.args[0])
        return 1

if __name__ == "__main__":
    sys.exit(main(sys.argv))
