#!/usr/bin/env python
#
# Copyright (c) rPath, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


import os
import sys

if os.path.dirname(sys.argv[0]) != ".":
    if sys.argv[0][0] == "/":
        fullPath = os.path.dirname(sys.argv[0])
    else:
        fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.insert(0, os.path.dirname(fullPath))

from conary import rpmhelper

def usage():
    print "Usage: rpm2cpio <rpmpackage> | cpio -ivumd"
    return 1

def main(argv):
    if len(argv) > 2 or len(argv) < 2:
        return usage()
    try:
        r = file(argv[1], 'r')
    except:
        return usage()

    try:
        rpmhelper.extractRpmPayload(r, sys.stdout)
    except rpmhelper.UnknownPayloadFormat, e:
        sys.stderr.write('payload is not in cpio format: %s\n' % e.args[0])
        return 1
    except rpmhelper.UnknownCompressionType, e:
        sys.stderr.write('compression type %s unknown\n' % e.args[0])
        return 1

if __name__ == "__main__":
    sys.exit(main(sys.argv))
