#!/usr/bin/python2.4
# -*- mode: python -*-
#
# Copyright (c) 2005 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.opensource.org/licenses/cpl.php.
#
# This program is distributed in the hope that it will be useful, but
# without any waranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

import gzip
import os
import re
import stat
import sys
import tempfile

import conary
import checkin
import conarycfg
import rpmhelper

from build import cook
from lib import util
from repository.netclient import NetworkRepositoryClient
from repository import errors


chkconfigRe = re.compile(r'([ \t]*)(/sbin/)?chkconfig.*')
serviceRe = re.compile(r'([ \t]*)(/sbin/)?service.*')
ldconfigRe = re.compile(r'([ \t]*)(/sbin/)?ldconfig.*')
userRe = re.compile(r'([ \t]*)(/usr/sbin/)?user(add|del).*')
groupRe = re.compile(r'([ \t]*)(/usr/sbin/)?group(add|del).*')
# a few duplicate install-info invocations shouldn't hurt anything
#installinfoRe = re.compile(r'([ \t]*)(/sbin/)?install-info.*')

# remove surrounding whitespace and quotes from a string
quotesRe = re.compile(r'[ \t]*"?(.*)"?[ \t]*')
# remove redirection
redirectionRe = re.compile(r'2?>.*')

(PRE, POST, PREUN, POSTUN) = range(0,4)


class taghandlerBuilder:
    def __init__(self, recipe):
        self.packagename = recipe.packagename
        self.recipe = recipe
        self.userinfo = {}
        self.groupinfo = {}
        self.scripts_exist = False
        self.scripts = {}

        rpmHeader = recipe.rpmHeader

        self.preScript = None
        if rpmhelper.PREIN in rpmHeader:
            # we will ignore the contents of preScript, except to try to
            # fetch user/group information from it
            self.preScript = self.removeUnConary(
                rpmHeader[rpmhelper.PREIN])

    def buildScripts(self):

        rpmHeader = self.recipe.rpmHeader

        triggers = None
        if rpmhelper.TRIGGERSCRIPTS in rpmHeader:
            triggers = True

        postScript = None
        if rpmhelper.POSTIN in rpmHeader:
            if rpmhelper.POSTINPROG in rpmHeader and \
               rpmHeader[rpmhelper.POSTINPROG] != '/bin/sh':
                postInProg = rpmHeader[rpmhelper.POSTINPROG]
                if 'ldconfig' in postInProg:
                    # ldconfig happens automatically
                    pass
                else:
                    print 'unhandled POSTIN interpreter %s' % postInProg
            else:
                postScript = self.removeUnConary(
                    rpmHeader[rpmhelper.POSTIN])
                if 'RPM_INSTALL_PREFIX' in postScript:
                    self.warnRelocation('post')
                    postScript = None
                if 'ld.so.conf' in postScript:
                    self.warnLdSoConf('post')

        preUn = None
        if rpmhelper.PREUN in rpmHeader:
            preUn = self.removeUnConary(rpmHeader[rpmhelper.PREUN])
            if 'RPM_INSTALL_PREFIX' in preUn:
                self.warnRelocation('preun')
                preUn = None
            if 'ld.so.conf' in preUn:
                self.warnLdSoConf('post')
                        

        postUn = None
        if rpmhelper.POSTUN in rpmHeader:
            postUn = self.removeUnConary(rpmHeader[rpmhelper.POSTUN])
            if rpmhelper.POSTUNPROG in rpmHeader and \
               rpmHeader[rpmhelper.POSTUNPROG] != '/bin/sh':
                postInProg = rpmHeader[rpmhelper.POSTUNPROG]
                if 'ldconfig' in postUnProg:
                    # ldconfig happens automatically
                    pass
                else:
                    print 'unhandled POSTUN interpreter %s' % postUnProg
            else:
                if 'RPM_INSTALL_PREFIX' in postUn:
                    self.warnRelocation('postun')
                    postUn = None
                if 'ld.so.conf' in postUn:
                    self.warnLdSoConf('postun')


        if self.preScript:
            print 'Conary does not implement pre scripts.'
            print 'Most pre scripts add users/groups, which conary does'
            print 'using r.User() and r.Group(); you may need to use the'
            print '--recipe option and manually modify or add r.User()'
            print 'and/or r.Group() lines.'
        if postUn:
            print 'Conary handles postuninstall in a way that is not'
            print 'compatible with RPM postun scripts.'
            print 'Use the --recipe option and manually modify the'
            print 'recipe, taghandler, or scripts as necessary.'
            print 'It is most likely that the postuninstall will be'
            print 'entirely unnecessary with Conary, since Conary'
            print 'handles things like ld.so.conf changes itself,'
            print 'and has tag handlers for system databases like'
            print 'info/dir, /etc/shells, and scrollkeeper.'
            print 'Also, be aware that many postuninstall scripts'
            print 'can really be run as preunistall scripts.'
        if triggers:
            print 'Conary does not implement triggers at all.'
            print 'Most triggers are workarounds for old bugs.'
            print 'The conary taghandler facility provides all the necessary'
            print 'semantics, but we cannot adapt them automatically.'
            print 'You will have to look at the triggers and implement any'
            print 'necessary semantics differently for Conary, using'
            print 'the --recipe option and manual modification using'
            print 'taghandlers.'
        if postScript:
            self.script(POST, postScript)
        if preUn:
            self.script(PREUN, preUn)

    def removeUnConary(self, script):
        # make parsing easier by removing \ line continuation
        script = ''.join(script.split('\\\n'))
        scriptLines = script.split('\n')
        # conary will deal with chkconfig automatically,
        # and we do not want to run it twice
        # adding users and groups should be done through Conary
        # removing users and groups should not be done, ever; it
        # is a security risk
        if 'chkconfig' in script or \
           'service' in script or \
           'ldconfig' in script or \
           'useradd' in script or \
           'userdel' in script or \
           'groupadd' in script or \
           'groupdel' in script:
            lines = []
            for line in scriptLines:
                if 'chkconfig' in line:
                    print 'removing chkconfig from "%s"' %line
                    line = chkconfigRe.sub(r'\1:', line)
                if 'service' in line:
                    print 'removing service from "%s"' %line
                    line = serviceRe.sub(r'\1:', line)
                if 'ldconfig' in line:
                    print 'removing ldconfig from "%s"' %line
                    line = ldconfigRe.sub(r'\1:', line)
                if 'useradd' in line:
                    print 'removing useradd from "%s"' %line
                    self.recorduser(line)
                    line = userRe.sub(r'\1:', line)
                if 'groupadd' in line:
                    print 'removing groupadd from "%s"' %line
                    self.recordgroup(line)
                    line = userRe.sub(r'\1:', line)
                if 'userdel' in line:
                    print 'removing userdel from "%s"' %line
                    line = userRe.sub(r'\1:', line)
                if 'groupdel' in line:
                    print 'removing groupdel from "%s"' %line
                    line = userRe.sub(r'\1:', line)
                lines.append(line)
            scriptLines = lines
        return scriptLines

    def warnRelocation(self, name):
        print '%%%s requires relocation.' %name
        print 'Conary does not implement relocatable packages.'
        print '%%%s will not be run' %name

    def warnLdSoConf(self, name):
        print '%%%s appears to modify ld.so.conf' %name
        print 'Conary manages ld.so.conf itself'
        print 'Please use --recipe and modify the %s script not to' %name
        print 'modify ld.so.conf'

    def recorduser(self, line):
        line = redirectionRe.sub('', line)
        user = line.split(" ")[-1]
        self.userinfo[user] = {}
        rest = " ".join(line.split(" ")[:-1])
        # we hope that there are no comments or homedirs with an embedded
        # "-" character.  If there are, maybe the default case saves us.
        # This is all heuristics anyway...
        args = rest.split("-")
        try:
            for index in range(0,len(args)):
                if 'useradd' in args[index]:
                    # skip program name, hope no one puts user name there
                    pass
                elif args[index][0] in 'refmMknop':
                    # we ignore these options
                    pass
                elif args[index][0] == 'c':
                    self.userinfo[user]['comment'] = self.getarg(args[index])            
                elif args[index][0] == 'd':
                    self.userinfo[user]['homedir'] = self.getarg(args[index])
                elif args[index][0] == 'u':
                    self.userinfo[user]['preferred_uid'] = self.getarg(args[index])
                elif args[index][0] == 's':
                    self.userinfo[user]['shell'] = self.getarg(args[index])
                elif args[index][0] == 'g':
                    self.userinfo[user]['group'] = self.getarg(args[index])
                    # XXX if this is a number, we'll have to later fill group
                    # name in from groupinfo, thanks to lots of broken RPM specs
                else:
                    # unknown option
                    print 'error parsing "%s"' %line
                    del self.userinfo[user]
                    return
            print 'storing user information: %s' %str(self.userinfo[user])
        except:
            print 'error parsing "%s"' %line
            del self.userinfo[user]
                
    def recordgroup(self, line):
        line = redirectionRe.sub('', line)
        group = line.split(" ")[-1]
        self.groupinfo[group] = {}
        rest = " ".join(line.split(" ")[:-1])
        args = rest.split("-")
        try:
            for index in range(0,len(args)):
                if 'groupadd' in args[index]:
                    # skip program name, hope no one puts group name there
                    pass
                elif args[index][0] in 'rof':
                    # we ignore these options
                    pass
                elif args[index][0] == 'g':
                    group = self.getarg(args[index])
                    self.groupinfo[group]['gid'] = self.getarg(args[index])
                else:
                    # unknown option
                    print 'error parsing "%s"' %line
                    del self.groupinfo[group]
                    return
            print 'storing group information: %s' %str(self.groupinfo[group])
        except:
            del self.groupinfo[group]
            print 'error parsing "%s"' %line

    def getarg(self, data):
        return commentRe.sub(r'\1', data[1:])

    def script(self, type, script):
        self.scripts_exist = True
        self.scripts[type] = script

    def exists(self):
        return self.scripts_exist

    def writefiles(self):
        # %(libexecdir)s/conary/rpm-scripts/%(name)s/{post,preun}
        # %(taghandlerdir)s/%(name)s
        # %(tagdescriptiondir)s/%(name)s
        if not self.exists():
            return

        self.taghandlername = self.packagename+'.taghandler'
        self.tagdescriptionname = self.packagename+'.tagdescription'
        self.postscriptname = self.packagename+'.rpmpost'
        self.preunname = self.packagename+'.rpmpostun'

        tagdescription = [
            'file          %(taghandlerdir)s/%(name)s',
            'description   %(name)s RPM script proxy handler',
            'datasource    args',
        ]

        taghandler = [
            '#!/bin/bash',
            'case $2 in',
        ]

        if POST in self.scripts:
            taghandler.extend([
                '    update)',
                '        %(libexecdir)s/conary/rpm-scripts/%(name)s/post 1',
                '        ;;',
            ])
            tagdescription.append('implements    files update')
            writeLines(self.postscriptname, self.scripts[POST])
        if PREUN in self.scripts:
            taghandler.extend([
                '    remove)',
                '        %(libexecdir)s/conary/rpm-scripts/%(name)s/postun 0',
                '        ;;',
            ])
            tagdescription.append('implements    files preremove')
            writeLines(self.preunname, self.scripts[PREUN])

        taghandler.extend([
            'esac',
            'exit 0',
        ])
        writeLines(self.tagdescriptionname, tagdescription)
        writeLines(self.taghandlername, taghandler)

    def sourcefiles(self):
        sourcefiles = [self.taghandlername, self.tagdescriptionname]
        if POST in self.scripts:
            sourcefiles.append(self.postscriptname)
        if PREUN in self.scripts:
            sourcefiles.append(self.preunname)
        return sourcefiles

    def recipelines(self):
        # note that we cannot do r.TagSpec('%(name)s',... because
        # tag specs cannot have macros embedded in them
        recipelines = [
            "",
            "        r.addSource('"+self.taghandlername+"', dest='%(taghandlerdir)s%(name)s', macros=True)",
            "        r.addSource('"+self.tagdescriptionname+"', dest='%(tagdescriptiondir)s%(name)s', macros=True)",
            "        # this file needs to have different contents in each build",
            "        # in order for rpm script update conventions to work",
            "        # some random data should be good enough",
            "        r.Create('/usr/lib/conary/rpm-scripts/%(name)s/updatefile')",
            "        r.Run('dd if=/dev/random bs=64 count=1 | md5sum > %(destdir)s/usr/lib/conary/rpm-scripts/%(name)s/updatefile')",
            "        r.TagSpec(r.name, '/usr/lib/conary/rpm-scripts/%(name)s/updatefile')"
        ]
        if POST in self.scripts:
            recipelines.append(
                "        r.addSource('"+self.postscriptname+"', dest='%(libexecdir)s/conary/rpm-scripts/%(name)s/post', macros=True)"
            )
        if PREUN in self.scripts:
            recipelines.append(
                "        r.addSource('"+self.preunname+"', dest='%(libexecdir)s/conary/rpm-scripts/%(name)s/preun', macros=True)"
            )
        return recipelines


class recipeBuilder:
    def __init__(self, rpmfile, rpmname, packageScripts):
        self.rpmHeader = rpmhelper.readHeader(rpmfile)
        self.packagebasename = self.rpmHeader[rpmhelper.NAME]
        self.packagename = 'rpm_'+self.packagebasename
        self.recipename = self.packagename + '.recipe'
        # get information from RPM
        rpmdata = {}
        rpmdata['classname'] = '_'.join(self.packagename.split('-'))
        rpmdata['packagename'] = self.packagename
        rpmdata['version'] = '_'.join((
            self.rpmHeader[rpmhelper.VERSION],
            self.rpmHeader[rpmhelper.RELEASE]))
        rpmdata['rpmname'] = os.path.basename(rpmname)

        self.recipe = [
            "class %(classname)s(PackageRecipe):" %rpmdata,
            "    name = '%(packagename)s'" %rpmdata,
            "    version = '%(version)s'" %rpmdata,
            "",
            "    def setup(r):",
            "        r.addArchive('%(rpmname)s', dir='/')" %rpmdata,
            "",
            "        # by default, we do not split RPMs up into components",
            "        r.ComponentSpec('runtime', '.*')",
            "",
            "        # RPMs may not follow conary rules for config files for",
            "        # each file in /etc, so we'll stick to only files marked",
            "        # as config files in the RPM proper",
            "        r.EtcConfig(exceptions='.*')",
            "",
            "        # We also need to disable a lot of other policy that is",
            "        # very useful when building software, but not when",
            "        # trying to repackage something essentially unchanged.",
            "        r.RemoveNonPackageFiles(exceptions='.*')",
            "        r.FixupMultilibPaths(exceptions='.*')",
            "        r.ExecutableLibraries(exceptions='.*')",
            "        r.Strip(exceptions='.*')",
            "        r.NormalizeCompression(exceptions='.*')",
            "        r.NonBinariesInBindirs(exceptions='.*')",
            "        r.FilesInMandir(exceptions='.*')",
            "        r.BadInterpreterPaths(exceptions='.*')",
            "        r.ImproperlyShared(exceptions='.*')",
            "        r.CheckSonames(exceptions='.*')",
            "        r.RequireChkconfig(exceptions='.*')",
            "        r.CheckDestDir(exceptions='.*')",
            "        r.DanglingSymlinks(exceptions='.*')",
            "        r.WarnWriteable(exceptions='.*')",
            "        r.WorldWriteableExecutables(exceptions='.*')",
            "        # ObsoletePaths does not honor exceptions",
            "        del r.ObsoletePaths",
            "        r.IgnoredSetuid(exceptions='.*')",
            "",
        ]

        users = {}
        groups = {}
        directories = []
        filled_directories = []
        included_directories = []
        info_directories = {}
        tagfile = None
        for path, mode, rdev, flags, username, groupname in zip(
            self.rpmHeader.paths(),
            self.rpmHeader[rpmhelper.FILEMODES],
            self.rpmHeader[rpmhelper.FILERDEVS],
            self.rpmHeader[rpmhelper.FILEFLAGS],
            self.rpmHeader[rpmhelper.FILEUSERNAME],
            self.rpmHeader[rpmhelper.FILEGROUPNAME]):
            escaped_path = util.literalRegex(util.normpath(path))
            if username != 'root' or groupname != 'root':
                self.recipe.append(
                    "        r.Ownership('%s', '%s', r'%s')"
                    %(username, groupname, escaped_path))
                if username != 'root':
                    if username not in users:
                        users[username] = True
                if groupname != 'root':
                    if groupname not in groups:
                        groups[groupname] = True

            if stat.S_ISDIR(mode):
                directories.append(path)
                if mode & 7777 != 0755 or username != 'root' \
                   or groupname != 'root':
                    info_directories[path] = (mode, username, groupname)
                    self.recipe.append(
                        "        r.ExcludeDirectories(exceptions=r'%s')"
                        %escaped_path)
                    included_directories.append(path)
                    continue
            elif os.path.dirname(path) not in filled_directories:
                filled_directories.append(os.path.dirname(path))

            if stat.S_ISCHR(mode) or stat.S_ISBLK(mode):
                if stat.S_ISCHR(mode):
                    type='c'
                else:
                    type='b'
                # this is correct for 32-bit device number
                # RPM does not provide 64-bit device number
                minor = rdev & 0xff | (rdev >> 12) & 0xffffff00
                major = (rdev >> 8) & 0xfff
                self.recipe.append(
                    "        r.MakeDevices(r'%s', '%s', '%d', '%d', '%s', '%s', '0%o')"%
                    (escaped_path, type, major, minor, username, groupname,
                     mode&0777))
                continue
            
            if mode & 07000:
                self.recipe.append(
                    "        r.SetModes(r'%s', 0%o)"%(escaped_path, mode & 07777))

            if flags & 1:
                # config file
                self.recipe.append(
                    "        r.Config(r'%s')" %escaped_path)


        for dir in directories:
            if dir not in filled_directories and \
               dir not in included_directories:
                self.recipe.append(
                    "        r.ExcludeDirectories(exceptions=r'%s')"
                    % util.literalRegex(dir))

        
        # pull user/group definition information, if any, out of the scripts
        self.tag = taghandlerBuilder(self)

        # XXX add any User/Group bits needed for this recipe -- guess from
        # current system first, then by trying to parse any adduser/group
        # lines (or maybe the other way around?)

        if packageScripts:
            self.tag.buildScripts()

    def name(self):
        return self.recipename

    def write(self):
        if self.tag and self.tag.exists():
            self.tag.writefiles()
            checkin.addFiles(self.tag.sourcefiles(), ignoreExisting=True)
            self.recipe.extend(self.tag.recipelines())

        writeLines(self.recipename, self.recipe)


def writeLines(filename, lines):
    f = open(filename, 'w')
    f.write('\n'.join(lines))
    f.close()
    

def usage():
    print "\n".join((
        'Usage: rpm2ccs [options] <rpmpackage>',
        'Options: --recipe|--changeset|--update',
        '           --recipe just writes a recipe',
        '           --changeset (default) creates a changeset',
        '           --update cooks and updates a changeset on the local system',
        '         --ignore-scripts ignores RPM scripts, relying instead on',
        "           Conary's automated policy for all actions",
        '         --no-clean keeps conary from cleaning up after the build',
        '         --commit tells conary to commit changes to the repository',
        '',
        ))
    return 1

(RECIPE, CHANGESET, UPDATE) = range(0,3)

def main(argv):
    if len(argv) < 2:
        return usage()
    rpmname = argv[-1]
    if '/' not in rpmname:
        rpmname = os.sep.join((os.getcwd(), rpmname))
    try:
        rpmfile = file(rpmname, 'r')
    except:
        return usage()

    cfg = conarycfg.ConaryConfiguration()
    repos = NetworkRepositoryClient(cfg.repositoryMap)

    create = CHANGESET
    if '--recipe' in argv:
        create = RECIPE
    elif '--changeset' in argv:
        create = CHANGESET
    elif '--update' in argv:
        create = UPDATE
        print '--update is not yet implemented, sorry'
        return 1
    
    packageScripts = True
    if '--ignore-scripts' in argv:
        packageScripts = False

    cfg.noClean = False
    if '--no-clean' in argv:
        cfg.noClean = True

    commitWork=False
    if '--commit' in argv:
        print 'warning: --commit is not yet finished'
        return 1
        commitWork=True

    sys.excepthook = util.genExcepthook(cfg.dumpStackOnError)

    recipe = recipeBuilder(rpmfile, rpmname, packageScripts)

    dir = tempfile.mkdtemp('',
                           ''.join(('rpm2ccs-', recipe.packagebasename, '-')))
    os.chdir(dir)

    packagedir = util.joinPaths(dir, recipe.packagename)

    try:
        # if it is already in the repository, pull it out
        repos.findTrove(cfg.buildLabel, recipe.packagename+':source',
                        None, None)
        checkin.checkout(repos, cfg, packagedir, recipe.packagename)
    except errors.TroveNotFound:
        checkin.newPackage(repos, cfg, recipe.packagename)

    os.chdir(packagedir)

    recipe.write()
    checkin.addFiles((recipe.name(),), ignoreExisting=True)
    util.copyfile(rpmname,
                  util.joinPaths(packagedir, os.path.basename(rpmname)))
    checkin.addFiles((os.path.basename(rpmname),), ignoreExisting=True)


    if create == RECIPE:
        print 'Recipe and any other necessary files in %s' % packagedir
        return 0


    if commitWork:
        checkin.commit(repos, cfg, None, True)
        cook.cookCommand(cfg, (recipe.packagename,), False, {}, resume=False)
        if cfg.noClean:
            print 'Not deleting working directory %s' % dir
        else:
            util.rmtree(dir)

    else:
        cook.cookCommand(cfg, (recipe.name(),), False, {}, resume=False)
        print 'Changeset and other files in %s' % packagedir
        

if __name__ == "__main__":
    sys.exit(main(sys.argv))
