#!/usr/bin/env python
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


"""
Shows those paths on your local system that are owned by multiple 
components
"""

import os
import sys

if os.path.dirname(sys.argv[0]) != ".":
    if sys.argv[0][0] == "/":
        fullPath = os.path.dirname(sys.argv[0])
    else:
        fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.insert(0, os.path.dirname(fullPath))

from conary import conarycfg
from conary.local import database
from conary.lib import util
sys.excepthook = util.genExcepthook()

def main():
    cfg = conarycfg.ConaryConfiguration()
    db = database.Database(cfg.root, cfg.dbPath)
    displayConflicts(db, cfg)

def displayConflicts(db, cfg):
    for (trove1, trove2, path) in iterPathConflicts(db.db):
	print "%-20s  %-20s  %-30s" % (trove1[0], trove2[0], path)	

def iterPathConflicts(sqldb_obj):
    cu = sqldb_obj.db.cursor()
    cu.execute("""SELECT a.instanceId,b.instanceId,a.path 
		  FROM DBTroveFiles AS a, DBTroveFiles AS b
		  WHERE a.path=b.path 
		  AND a.instanceId != b.instanceID AND
		  a.isPresent=1 AND b.isPresent=1 AND
		  a.instanceID <= b.instanceID""")
    for row in cu:
	troveId1 = sqldb_obj.instances.getId(row[0])
	troveId2 = sqldb_obj.instances.getId(row[1])
        yield (troveId1, troveId2, row[2])

main()
