#!/usr/bin/python

import os
import sys

if os.path.dirname(sys.argv[0]):
    if sys.argv[0][0] == "/":
	fullPath = os.path.dirname(sys.argv[0])
    else:
	fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.append(os.path.dirname(fullPath))
from changeset import ChangeSet

cs = ChangeSet()
cs.readFile(sys.argv[1])
cs.formatToFile(sys.stdout)
