#!/usr/bin/python2.4
# -*- mode: python -*-
#
# Copyright (c) 2004 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.opensource.org/licenses/cpl.php.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

import cPickle
import hotshot.stats
import sys

def progress(msg):
    sys.stderr.write(msg + '\n')
    sys.stderr.flush()

def usage():
    print 'usage: %s profile [pickle output]'
    sys.exit(1)

if len(sys.argv) < 2 or len(sys.argv) > 3:
    usage()

filename = sys.argv[1]
picklefilename = None
if len(sys.argv) == 3:
    picklefilename = sys.argv[2]

if filename.endswith('.pickle'):
    if picklefilename:
        print 'input file is pickled and an output pickle name is specified'
        usage()
    f = open(filename)
    stats = cPickle.load(f)
else:    
    progress('loading %s' %filename)
    stats = hotshot.stats.load(filename)

if picklefilename:
    f = open(sys.argv[2], 'w')
    cPickle.dump(stats, f)
else:
    stats.sort_stats('time', 'calls')
    stats.print_stats()
