#!/usr/bin/env python
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


""" Finds file(s) matching the given regexp that are unowned """

import os
import re
import sys

if os.path.dirname(sys.argv[0]) != ".":
    if sys.argv[0][0] == "/":
        fullPath = os.path.dirname(sys.argv[0])
    else:
        fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.insert(0, os.path.dirname(fullPath))

from conary import conarycfg
from conary.deps import deps
from conary.local import database
from conary.lib import util
from conary import versions
from conary import updatecmd

def usage():
    print """\
Usage: unowned [-r] <file>+
         """
    return 1

sys.excepthook = util.genExcepthook()


def main(argv):
    if argv < 2:
        return usage()
    if len(argv) > 1 and argv[1] == '-r':
        recursive = True
        pathList = argv[2:]
    else:
        recursive = False
        pathList = argv[1:]

    if not pathList:
        return usage()

    expandedPathList = []
    for path in pathList:
        expandedPathList.extend(util.braceGlob(os.path.abspath(util.normpath(path))))

    cfg = conarycfg.ConaryConfiguration()
    db = database.Database(cfg.root, cfg.dbPath)
    for path in pathList:
        if not os.path.isdir(path) or not recursive:
            found = False
            for trove in db.iterTrovesByPath(path):
                found = True
                break
            if not found:
                unownedFile(path)
        else:
            for (root, dirnames, fileNames) in os.walk(path):
                dirnames.sort()
                found = False
                for fileName in sorted(fileNames):
                    filePath = root + '/' + fileName
                    for trove in db.iterTrovesByPath(filePath):
                        found = True
                        break
                    if not found:
                        unownedFile(filePath)

    return 0

def unownedFile(path):
    print path

if __name__ == "__main__":
    sys.exit(main(sys.argv))
