#!/usr/bin/python2.3
# -*- mode: python -*-
#
# Copyright (c) 2004 Specifix, Inc.
# All rights reserved
#

import os
import sys
import dbhash

if os.path.dirname(sys.argv[0]):
    if sys.argv[0][0] == "/":
	fullPath = os.path.dirname(sys.argv[0])
    else:
	fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.append(os.path.dirname(fullPath))

import srscfg
import versions
import versioned

cfg = srscfg.SrsConfiguration()

if len(sys.argv) > 2:
    db = versioned.Database(sys.argv[1], "r")
    f = db.openFile(sys.argv[2])
    if len(sys.argv) == 3:
	for branch in f.branchList():
	    print "%s:" % branch.asString()
	    print "\n".join(map(lambda x: "\t%s" % x.asString(branch), 
				f.versionList(branch)))
    else:
	final = f.getVersion(versions.VersionFromString(sys.argv[3], cfg.defaultbranch))
	sys.stdout.write("".join(final.readlines()))
else:
    db = versioned.FileIndexedDatabase(sys.argv[1], "r")
    print "\n".join(db.fileList())
