.\" Copyright (c) 2005 rPath, Inc.
.TH YUCK 1 "16 February 2005" "rPath, Inc."
.SH NAME
yuck \- temporary hack for updating conary-based systems
.SH SYNOPSIS
.B yuck [--missing] [--update] [--except <exception,...>]
.br
\ \ \ \ \ [--display|--display-only <displayparam>,<displayparam>]
.SH DESCRIPTION
\fByuck\fP is a temporary hack to allow you to update a
conary-based system.  It will go away as soon as planned
enhancements to groups make it unnecessary.
.SH REFERENCE
.TP
.PD 0
--display
.TP
.PD
--display-only \fIdiplayparam[,displayparm...]
Tell what parameters (columns) to display.  Choices are:
[no]change, name, local, version, flavor, repo
.TP
.PD
--except \fIexception[,exception...]
Ignore troves named as exceptions, which are specified as
regular expressions (use \fBtrovename$\fP to avoid unintentional
matches).   The kernel trove is excepted 
automatically, and must be updated by hand.
.TP
.PD
--missing
show troves on your installLabelPath that are not installed on
your system
.TP
.PD
--update
Attempt to install troves that are noted as out of date (or,
with --missing, that are missing)
.SH BUGS
Yuck exists.  You can consider this a bug.
Nevertheless, you can report bugs at http://bugs.rpath.com/
.\"
.\"
.\"
.SH "SEE ALSO"
conary(1)
.br
cvc(1)
.br
cvcdesc(1)
.br
http://www.rpath.com/
.br
http://wiki.conary.com/
.br
http://www.rpath.com/technology/conary.html
.I An Introduction to the Conary Software Provisioning System
.br
http://www.rpath.com/technology/techoverview/
.I Repository-based System Management Using Conary
