#!/usr/bin/env python
import os
import sys

if os.path.dirname(sys.argv[0]) != ".":
    if sys.argv[0][0] == "/":
        fullPath = os.path.dirname(sys.argv[0])
    else:
        fullPath = os.getcwd() + "/" + os.path.dirname(sys.argv[0])
else:
    fullPath = os.getcwd()

sys.path.insert(0, os.path.dirname(fullPath))

from conary import files
from conary.repository.netrepos import netserver

cfgpath = sys.argv[1]
cfg = netserver.ServerConfig()
cfg.read(cfgpath)
netrepos = netserver.NetworkRepositoryServer(cfg, '')
cu = netrepos.db.cursor()
cu.execute("SELECT stream FROM FileStreams WHERE stream IS NOT NULL")
for fileStream, in cu:
    if (not files.frozenFileFlags(fileStream).isEncapsulatedContent()
            and files.frozenFileHasContents(fileStream)):
        cont = files.frozenFileContentInfo(fileStream)
        sha1 = cont.sha1()
        if not netrepos.repos._hasFileContents(sha1):
            print sha1.encode('hex')
